plugin 'cocoapods-swift-modular-headers'

ws_dir = Pathname.new(__dir__)
ws_dir = ws_dir.parent until
  File.exist?("#{ws_dir}/node_modules/react-native-test-app/test_app.rb") ||
  ws_dir.expand_path.to_s == '/'
require "#{ws_dir}/node_modules/react-native-test-app/test_app.rb"

workspace 'ReactNativeBottomTabsExample.xcworkspace'

apply_modular_headers_for_swift_dependencies()

use_test_app!
